version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    #command: gunicorn desafio_aiqfome.wsgi --bind 0.0.0.0:8000 -w 4
    command: /app/.venv/bin/fastapi dev --port 80 --host 0.0.0.0
    volumes:
      - static_volume:/desafio_aiqfome/staticfiles
      - media_volume:/desafio_aiqfome/mediafiles
    ports:
      - 8000:80
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:17.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  # nginx:
  #   build: ./conf/nginx
  #   volumes:
  #     - static_volume:/desafio_aiqfome/staticfiles
  #     - media_volume:/desafio_aiqfome/mediafiles
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - web

volumes:
  postgres_data:
  static_volume:
  media_volume: